Automatically close toastr box on timeout if animation is failed
diegoddox/react-redux-toastr pull request #117
Opened 2017-04-11 19:23 UTC by jalkoby

I've made the second implementation - based on timeout, so a user is free to used own transitions. Please look at it(info toastr in the demo app) as I'm starting to like it more than the current

2017-04-11 20:09 UTC, diegoddox commented
What will happen if the the `toastr` has an option `timeOut:0`? I guess that it will be removed anyway after the [timeout](https://github.com/diegoddox/react-redux-toastr/pull/117/commits/e7e46bdf1c40e56f596a53f371cb285b4cec9d7b#diff-2b4ca49d4bb0a774c4d4c1672d7aa781R83) is called.

2017-04-11 20:25 UTC, jalkoby commented
if set `timeOut: 0` a toast box stays opens forever as on end of transition never called 
 `if(0) === if(false)`

2017-04-11 20:28 UTC, diegoddox commented
True that!

2017-04-28 03:10 UTC, XanderDwyl requested changes

2017-04-28 03:10 UTC, XanderDwyl commented on development/Menu.js
> +              transitionOut: 'bounceOutU'
wrong spelling, might be `bounceOutUp`?

2017-04-28 07:05 UTC, diegoddox commented on development/Menu.js
> +              transitionOut: 'bounceOutU'
I think that was by design in order to test the timeout function.

2017-04-28 07:09 UTC, XanderDwyl commented on development/Menu.js
> +              transitionOut: 'bounceOutU'
👍

2017-04-28 19:00 UTC, jalkoby commented on development/Menu.js
> +              transitionOut: 'bounceOutU'
Exactly 😎

2017-04-28 19:03 UTC, jalkoby commented on development/Menu.js
> +              transitionOut: 'bounceOutU'
The idea behind this pr is to allow a user to use any css class, but close a popup in an invalid case as well

2017-06-15 13:44 UTC, VincentN commented
Hey @diegoddox, can this be merged in please? ^^ Thanks a lot!

2017-06-15 19:05 UTC, jalkoby commented
It was a show case for the automatic close case

2017-07-25 10:01 UTC, diegoddox commented
I'm will not be able to test but will merge!!

2017-07-25 10:02 UTC, merged